### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by UsamaKarim** [vigov5/nodium#2]
Medium might have changes and the extension it broken

**Comment by vigov5** [comment]
@UsamaKarim thank you for your report, I'll take a look at this bug.

**Comment by vigov5** [comment]
@UsamaKarim I've just checked with some sites on Edge browser, it seems still functional. Can you tell me some info:
- Which browser and version you are using (Firefox, Chrome, Edge)?
- URL that Nodium is not working for you?

Best regards,

**Comment by UsamaKarim** [comment]
\
> 
> * Which browser and version you are using (Firefox, Chrome, Edge)?
> * URL that Nodium is not working for you?

I am using Chrome Version 89.0.4389.82 (Official Build) (64-bit), and none of URL is working

**Comment by vigov5** [comment]
@UsamaKarim It seems if you already on a Medium post, and click on the paywall link, It won't work but if you reload the page again, the paywall will be bypassed. Can you confirm this?
I'll take a deeper look when I have free time.

**Comment by UsamaKarim** [comment]
I can see the banner displaying that the domain has been added. Then I reload the page, nothing works. Even on medium.com it still displays a paywall. I even tried disabling my adblocker but still in vain

![image](https://user-images.githubusercontent.com/64292174/114315225-69696500-9b17-11eb-8b6a-35eb1c2e4829.png)

**Comment by vigov5** [comment]
@UsamaKarim thank you, I confirmed this one, investigated the new medium's js code, and found a way to workaround. For now, it worked but it's not generic enough to work when Medium updates new code. After I clear this problem, I will release a new version immediately 🙌

**Comment by vigov5** [comment]
@UsamaKarim I released new version v2.0. Firefox version got approved, while Chrome version is still pending for review. In the meantime, could you mind load the unpacked extension from GitHub and check if it works for you? thanks!

**Comment by UsamaKarim** [comment]
Hope so it's working on page refresh but I'll update you after more tests.

BTW I get this error
![image](https://user-images.githubusercontent.com/64292174/114983627-4ab5f600-9eaa-11eb-8518-73032a18079d.png)

**Comment by vigov5** [comment]
@UsamaKarim yeah, it's a known issue, https://github.com/vigov5/nodium/issues/ but not a deal-breaker, so I'll fix it when I have time :)
