### ISSUE TITLE
Not working on new Medium UI

### ISSUE THREAD

**Issue by hungdoansy** [vigov5/nodium#3]
This extension didn't seem to work on new Medium UI.
I turned the ext on and refreshed a medium article, it redirected to /undefined.

**Comment by vigov5** [comment]
@hungdoansy thank you for your report, I'm working on a fix right now.

**Comment by vigov5** [comment]
@hungdoansy I fixed the extension to work with the new UI. Could you mind loading the unpacked extension or install from the release page of GitHub and checking if it works for you? Thanks!

**Comment by hungdoansy** [comment]
> 

It worked fine on my Chrome. Thanks so much
