### ISSUE TITLE
Manifest version 2 is deprecated

### ISSUE THREAD

**Issue by tnmquann** [vigov5/nodium#5]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
![image](https://user-images.githubusercontent.com/56569936/201575971-d83b9d91-12ea-4c32-9ec6-0d15bb1e1ca5.png)

**Comment by vigov5** [comment]
@tnmquann Fixed with new release. Cheer!

**Comment by tnmquann** [comment]
> @tnmquann Fixed with new release. Cheer!

It's working fine on my browser at the moment. Thank you so much
