### ISSUE TITLE
Not working since 20-01-23

### ISSUE THREAD

**Issue by Wasserkopp** [vigov5/nodium#6]
Hey, sadly it doesn't seem to work on my side anymore... no matter what browser I try or how often I force realod, the page gets unblocked for a second and then (while still loading) locked again, the same with all medium subdomains. I have checked the console and found "[NODIUM] The site is powered by Medium!". What can I do? (not a coder here!)

**Comment by vigov5** [comment]
@Wasserkopp Thank you. I'll check it.

**Comment by luongs3** [comment]
Still waiting @vigov5  =)))))

**Comment by tienna-0051** [comment]
@Wasserkopp @luongs3 sadly, (maybe after Twitter took over by Elon Musk), for member-only articles, referrer from Twitter doesn't work anymore. Now, when you access Medium, they set the **sid** cookie (for both not logged in and authenticated user) and track number of free article by it. But you still can read member-only freely article by deleting **sid** cookie (but this will log you out of the Medium account). After 3 artilcles, delete **sid* cookie. Repeat. This will not work if you're logged in.

I can write a extension that block Medium from setting cookie but that means I need to completely rewrite the extension. it'll take time so on ETA for now 😢 

In the mean time, please clear your cookie and it'll work 💪

**Comment by vigov5** [comment]
@Wasserkopp @luongs3 sadly, (maybe after Twitter took over by Elon Musk), for member-only articles, referrer from Twitter doesn't work anymore. Now, when you access Medium, they set the sid cookie (for both not logged in and authenticated user) and track number of free article by it. But you still can read member-only freely article by deleting sid cookie (but this will log you out of the Medium account). After 3 artilcles, delete *sid cookie. Repeat. This will not work if you're logged in.

I can write a extension that block Medium from setting cookie but that means I need to completely rewrite the extension. it'll take time so on ETA for now 😢

In the mean time, please clear your cookie and it'll work 💪

**Comment by a7993n** [comment]
If I can push code snippet to delete "sid" cookies in the extension

**Comment by vigov5** [comment]
@luongs3 @a7993n @Wasserkopp
I added a new code. Guys may want to check it before I create a release. Now, when the extension is enabled, you will not be able to sign in. Please click its icon to turn it on/off. Please let me know if it has any bugs or if it works for you. Cheer!

**Comment by vigov5** [comment]
close for now.

**Comment by piavgh** [comment]
@vigov5 : this fix also logs me out from my Chrome profile.
