### ISSUE TITLE
runtime.lastError: Cannot access contents

### ISSUE THREAD

**Issue by phuongdm1987** [vigov5/nodium#7]
Unchecked runtime.lastError: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
Unchecked runtime.lastError: Cannot access a chrome:// URL

Seem we have permission issue, please help to fix, thanks

**Comment by vigov5** [comment]
The extension does not need to access `chrome://` URL (which is Chrome extension page, etc) so that's normal.
